export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export ZSH=~/.oh-my-zsh

# zsh theme
ZSH_THEME="simple"

# disable auto-setting terminal title
DISABLE_AUTO_TITLE="true"

# plugins
plugins=(
  git
  tmux
  pip
  docker
  npm
)

# init oh-my-zsh
source $ZSH/oh-my-zsh.sh

# fetch dotfile path
export SHELL_RC=$(readlink ~/.zshrc)
export DOT_HOME=${SHELL_RC%/package*}

# alias
alias vizshrc="vi $DOT_HOME/package/zsh/zshrc && source $SHELL_RC"

# load package config
for config in $DOT_HOME/package/**/*rc.sh; do
  source "$config"
done

# load custom config
if ls $DOT_HOME/custom/ | grep -Eqs ".*rc\.sh"; then
  unset config
  for config in $DOT_HOME/custom/*rc.sh; do
    source "$config"
  done
fi
