export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export ZSH=~/.oh-my-zsh

# zsh theme
ZSH_THEME="simple"

# disable auto-setting terminal title
DISABLE_AUTO_TITLE="true"

# plugins
plugins=(
  git
  tmux
  pip
  docker
  npm
)

# init oh-my-zsh
source $ZSH/oh-my-zsh.sh

# fetch dotfile path
export SHELLRC=$(readlink ~/.zshrc)
export DOT_HOME=${SHELLRC%/package*}

# load package config
for config in $DOT_HOME/package/**/*rc.sh; do
  [ -f "$config" ] && source "$config"
done

# load custom config
if ls $DOT_HOME/custom/ | grep -Eqs ".*rc\.sh"; then
  unset config
  for config in $DOT_HOME/custom/*rc.sh; do
    [ -f "$config" ] && source "$config"
  done
fi
