export PATH=/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export ZSH=~/.oh-my-zsh

ZSH_THEME="simple"

# disable auto-setting terminal title
DISABLE_AUTO_TITLE="true"

plugins=(
  tmux
  direnv
  httpie
  nvm
  pipenv
)

# init oh-my-zsh
source $ZSH/oh-my-zsh.sh

# init needle
source ~/.needle/needle.sh
