export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export ZSH=~/.oh-my-zsh

# zsh theme
ZSH_THEME="simple"

# disable auto-setting terminal title
DISABLE_AUTO_TITLE="true"

# plugins
plugins=(
  git
  tmux
  pip
  docker
  npm
)

# init oh-my-zsh
source $ZSH/oh-my-zsh.sh

# load custom plugin from needle
[ -f ~/.needle/plugin.sh ] && source ~/.needle/plugin.sh
